# -*- encoding: utf-8 -*-

=begin
#DocSpring API

#DocSpring provides an API that helps you fill out and sign PDF templates.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "docspring/version"

Gem::Specification.new do |s|
  s.name        = "docspring"
  s.version     = DocSpring::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["DocSpring"]
  s.email       = ["support@docspring.com"]
  s.homepage    = "https://github.com/DocSpring/docspring-ruby"
  s.summary     = "DocSpring API Client"
  s.description = "Client library for the DocSpring PDF generation and e-signature service"
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
