=begin
#DocSpring API

#DocSpring provides an API that helps you fill out and sign PDF templates.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DocSpring::PDFApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PDFApi' do
  before do
    # run before each test
    @api_instance = DocSpring::PDFApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PDFApi' do
    it 'should create an instance of PDFApi' do
      expect(@api_instance).to be_instance_of(DocSpring::PDFApi)
    end
  end

  # unit tests for add_fields_to_template
  # Add new fields to a Template
  # @param template_id 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [TemplateAddFieldsResponse]
  describe 'add_fields_to_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for batch_generate_pdfs
  # Generates multiple PDFs
  # @param data 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :wait Wait for submission batch to be processed before returning. Set to false to return immediately. Default: true (on sync.* subdomain)
  # @return [BatchGeneratePdfs201Response]
  describe 'batch_generate_pdfs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for combine_pdfs
  # Merge submission PDFs, template PDFs, or custom files
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [CreateCombinedSubmissionResponse]
  describe 'combine_pdfs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for combine_submissions
  # Merge generated PDFs together
  # @param data 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :wait Wait for combined submission to be processed before returning. Set to false to return immediately. Default: true (on sync.* subdomain)
  # @return [CreateCombinedSubmissionResponse]
  describe 'combine_submissions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for copy_template
  # Copy a Template
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @option opts [CopyTemplateOptions] :options 
  # @return [TemplatePreview]
  describe 'copy_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_custom_file_from_upload
  # Create a new custom file from a cached presign upload
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [CreateCustomFileResponse]
  describe 'create_custom_file_from_upload test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_data_request_event
  # Creates a new event for emailing a signee a request for signature
  # @param data_request_id 
  # @param event 
  # @param [Hash] opts the optional parameters
  # @return [CreateSubmissionDataRequestEventResponse]
  describe 'create_data_request_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_data_request_token
  # Creates a new data request token for form authentication
  # @param data_request_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :type 
  # @return [CreateSubmissionDataRequestTokenResponse]
  describe 'create_data_request_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_folder
  # Create a folder
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Folder]
  describe 'create_folder test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_html_template
  # Create a new HTML template
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [TemplatePreview]
  describe 'create_html_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_pdf_template
  # Create a new PDF template with a form POST file upload
  # @param template_document 
  # @param template_name 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :wait Wait for template document to be processed before returning. Set to false to return immediately. Default: true (on sync.* subdomain)
  # @option opts [String] :template_description 
  # @option opts [String] :template_parent_folder_id 
  # @return [TemplatePreview]
  describe 'create_pdf_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_pdf_template_from_upload
  # Create a new PDF template from a cached presign upload
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [TemplatePreview]
  describe 'create_pdf_template_from_upload test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_folder
  # Delete a folder
  # @param folder_id 
  # @param [Hash] opts the optional parameters
  # @return [Folder]
  describe 'delete_folder test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_template
  # Delete a template
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :version 
  # @return [TemplateDeleteResponse]
  describe 'delete_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for expire_combined_submission
  # Expire a combined submission
  # @param combined_submission_id 
  # @param [Hash] opts the optional parameters
  # @return [CombinedSubmission]
  describe 'expire_combined_submission test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for expire_submission
  # Expire a PDF submission
  # @param submission_id 
  # @param [Hash] opts the optional parameters
  # @return [SubmissionPreview]
  describe 'expire_submission test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for generate_pdf
  # Generates a new PDF
  # @param template_id 
  # @param submission 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :wait Wait for submission to be processed before returning. Set to false to return immediately. Default: true (on sync.* subdomain)
  # @return [CreateSubmissionResponse]
  describe 'generate_pdf test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for generate_pdf_for_html_template
  # Generates a new PDF for an HTML template
  # @param template_id 
  # @param submission 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :wait Wait for submission to be processed before returning. Set to false to return immediately. Default: true (on sync.* subdomain)
  # @return [CreateSubmissionResponse]
  describe 'generate_pdf_for_html_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for generate_preview
  # Generated a preview PDF for partially completed data requests
  # @param submission_id 
  # @param [Hash] opts the optional parameters
  # @return [SuccessErrorResponse]
  describe 'generate_preview test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_combined_submission
  # Check the status of a combined submission (merged PDFs)
  # @param combined_submission_id 
  # @param [Hash] opts the optional parameters
  # @return [CombinedSubmission]
  describe 'get_combined_submission test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_data_request
  # Look up a submission data request
  # @param data_request_id 
  # @param [Hash] opts the optional parameters
  # @return [SubmissionDataRequestShow]
  describe 'get_data_request test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_full_template
  # Fetch the full attributes for a PDF template
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @return [Template]
  describe 'get_full_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_presign_url
  # Get a presigned URL so that you can upload a file to our AWS S3 bucket
  # @param [Hash] opts the optional parameters
  # @return [UploadPresignResponse]
  describe 'get_presign_url test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_submission
  # Check the status of a PDF
  # @param submission_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_data 
  # @return [Submission]
  describe 'get_submission test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_submission_batch
  # Check the status of a submission batch job
  # @param submission_batch_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_submissions 
  # @return [SubmissionBatchWithSubmissions]
  describe 'get_submission_batch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_template
  # Check the status of an uploaded template
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @return [TemplatePreview]
  describe 'get_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_template_schema
  # Fetch the JSON schema for a template
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @return [JsonSchema]
  describe 'get_template_schema test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_combined_submissions
  # Get a list of all combined submissions
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Default: 1
  # @option opts [Integer] :per_page Default: 50
  # @return [Array<CombinedSubmission>]
  describe 'list_combined_submissions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_folders
  # Get a list of all folders
  # @param [Hash] opts the optional parameters
  # @option opts [String] :parent_folder_id Filter By Folder Id
  # @return [Array<Folder>]
  describe 'list_folders test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_submissions
  # List all submissions
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @option opts [Float] :limit 
  # @option opts [String] :created_after 
  # @option opts [String] :created_before 
  # @option opts [String] :type 
  # @option opts [Boolean] :include_data 
  # @return [ListSubmissionsResponse]
  describe 'list_submissions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_template_submissions
  # List all submissions for a given template
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @option opts [Float] :limit 
  # @option opts [String] :created_after 
  # @option opts [String] :created_before 
  # @option opts [String] :type 
  # @option opts [Boolean] :include_data 
  # @return [ListSubmissionsResponse]
  describe 'list_template_submissions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_templates
  # Get a list of all templates
  # @param [Hash] opts the optional parameters
  # @option opts [String] :query Search By Name
  # @option opts [String] :parent_folder_id Filter By Folder Id
  # @option opts [Integer] :page Default: 1
  # @option opts [Integer] :per_page Default: 50
  # @return [Array<TemplatePreview>]
  describe 'list_templates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for move_folder_to_folder
  # Move a folder
  # @param folder_id 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Folder]
  describe 'move_folder_to_folder test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for move_template_to_folder
  # Move Template to folder
  # @param template_id 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [TemplatePreview]
  describe 'move_template_to_folder test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for publish_template_version
  # Publish a template version
  # @param template_id 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [TemplatePublishVersionResponse]
  describe 'publish_template_version test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for rename_folder
  # Rename a folder
  # @param folder_id 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Folder]
  describe 'rename_folder test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for restore_template_version
  # Restore a template version
  # @param template_id 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [SuccessErrorResponse]
  describe 'restore_template_version test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for test_authentication
  # Test Authentication
  # @param [Hash] opts the optional parameters
  # @return [SuccessErrorResponse]
  describe 'test_authentication test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_data_request
  # Update a submission data request
  # @param data_request_id 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [CreateSubmissionDataRequestResponse]
  describe 'update_data_request test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_template
  # Update a Template
  # @param template_id 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [SuccessMultipleErrorsResponse]
  describe 'update_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
