=begin
#DocSpring API

#DocSpring provides an API that helps you fill out and sign PDF templates.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DocSpring::CombinedSubmissionAction
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe DocSpring::CombinedSubmissionAction do
  let(:instance) { DocSpring::CombinedSubmissionAction.new }

  describe 'test an instance of CombinedSubmissionAction' do
    it 'should create an instance of CombinedSubmissionAction' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(DocSpring::CombinedSubmissionAction)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "integration_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "state"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["pending", "processed", "failed", "error"])
      # validator.allowable_values.each do |value|
      #   expect { instance.state = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "action_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["webhook", "slack_webhook", "email", "aws_s3_upload"])
      # validator.allowable_values.each do |value|
      #   expect { instance.action_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "action_category"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["notification", "file_upload"])
      # validator.allowable_values.each do |value|
      #   expect { instance.action_category = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "result_data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
