=begin
#DocSpring API

#DocSpring provides an API that helps you fill out and sign PDF templates.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DocSpring::RenameFolderData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe DocSpring::RenameFolderData do
  let(:instance) { DocSpring::RenameFolderData.new }

  describe 'test an instance of RenameFolderData' do
    it 'should create an instance of RenameFolderData' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(DocSpring::RenameFolderData)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
