=begin
#API v1

#DocSpring is a service that helps you fill out and sign PDF templates.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

# Common files
require 'docspring/api_client'
require 'docspring/api_error'
require 'docspring/version'
require 'docspring/configuration'

# Models
require 'docspring/models/add_fields_data'
require 'docspring/models/add_fields_template_response'
require 'docspring/models/authentication_error'
require 'docspring/models/authentication_success_response'
require 'docspring/models/combine_pdfs_data'
require 'docspring/models/combined_submission'
require 'docspring/models/combined_submission_action'
require 'docspring/models/combined_submission_data'
require 'docspring/models/copy_template_data'
require 'docspring/models/create_combined_submission_response'
require 'docspring/models/create_custom_file_data'
require 'docspring/models/create_custom_file_response'
require 'docspring/models/create_folder_attributes'
require 'docspring/models/create_folder_data'
require 'docspring/models/create_html_template_data'
require 'docspring/models/create_submission_batch_response'
require 'docspring/models/create_submission_batch_submissions_response'
require 'docspring/models/create_submission_data'
require 'docspring/models/create_submission_data_request_data'
require 'docspring/models/create_submission_data_request_event_request'
require 'docspring/models/create_submission_data_request_event_response'
require 'docspring/models/create_submission_data_request_token_response'
require 'docspring/models/create_submission_response'
require 'docspring/models/create_template_from_upload_data'
require 'docspring/models/data_request_token'
require 'docspring/models/delete_template_response'
require 'docspring/models/error_response'
require 'docspring/models/folder'
require 'docspring/models/full_template'
require 'docspring/models/html_template_data'
require 'docspring/models/html_template_data_webhook_options'
require 'docspring/models/invalid_request'
require 'docspring/models/invalid_request_single_error'
require 'docspring/models/list_submissions_response'
require 'docspring/models/move_folder_data'
require 'docspring/models/move_template_data'
require 'docspring/models/pending_template'
require 'docspring/models/preview_pdf_response'
require 'docspring/models/publish_template_version404_response'
require 'docspring/models/publish_template_version422_response'
require 'docspring/models/publish_template_version_response'
require 'docspring/models/publish_template_version_response_result'
require 'docspring/models/publish_version_data'
require 'docspring/models/rename_folder_data'
require 'docspring/models/restore_template_version_response'
require 'docspring/models/restore_version_data'
require 'docspring/models/submission'
require 'docspring/models/submission_action'
require 'docspring/models/submission_batch'
require 'docspring/models/submission_batch_data'
require 'docspring/models/submission_data'
require 'docspring/models/submission_data_batch_request'
require 'docspring/models/submission_data_request'
require 'docspring/models/submission_data_request_event'
require 'docspring/models/template'
require 'docspring/models/template_data'
require 'docspring/models/template_defaults'
require 'docspring/models/template_document'
require 'docspring/models/template_document_metadata'
require 'docspring/models/template_schema'
require 'docspring/models/update_data_request_response'
require 'docspring/models/update_submission_data_request_data'
require 'docspring/models/update_template_data'
require 'docspring/models/update_template_response'
require 'docspring/models/upload_presign'
require 'docspring/models/upload_template_data'

# APIs
require 'docspring/api/pdf_api'

# <--------------- BEGIN DOCSPRING CUSTOMIZATION ----------------->
# Description: Require our custom API client class with polling support
require 'docspring/api/client'
# <--------------- BEGIN DOCSPRING CUSTOMIZATION ----------------->

module DocSpring
  class << self
    # Customize default settings for the SDK using block.
    #   DocSpring.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
