=begin
#DocSpring API

#DocSpring provides an API that helps you fill out and sign PDF templates.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

# Common files
require 'docspring/api_client'
require 'docspring/api_error'
require 'docspring/version'
require 'docspring/configuration'

# Models
require 'docspring/models/add_fields_data'
require 'docspring/models/batch_generate_pdfs201_response'
require 'docspring/models/combine_pdfs_data'
require 'docspring/models/combined_submission'
require 'docspring/models/combined_submission_action'
require 'docspring/models/combined_submission_data'
require 'docspring/models/copy_template_options'
require 'docspring/models/create_combined_submission_response'
require 'docspring/models/create_custom_file_data'
require 'docspring/models/create_custom_file_response'
require 'docspring/models/create_folder_data'
require 'docspring/models/create_html_submission_data'
require 'docspring/models/create_html_template'
require 'docspring/models/create_pdf_submission_data'
require 'docspring/models/create_pdf_template'
require 'docspring/models/create_submission_data_request_data'
require 'docspring/models/create_submission_data_request_event_request'
require 'docspring/models/create_submission_data_request_event_response'
require 'docspring/models/create_submission_data_request_response'
require 'docspring/models/create_submission_data_request_token_response'
require 'docspring/models/create_submission_response'
require 'docspring/models/custom_file'
require 'docspring/models/error_response'
require 'docspring/models/folder'
require 'docspring/models/json_schema'
require 'docspring/models/list_submissions_response'
require 'docspring/models/move_folder_data'
require 'docspring/models/move_template_data'
require 'docspring/models/multiple_errors_response'
require 'docspring/models/publish_version_data'
require 'docspring/models/rename_folder_data'
require 'docspring/models/restore_version_data'
require 'docspring/models/submission'
require 'docspring/models/submission_action'
require 'docspring/models/submission_batch'
require 'docspring/models/submission_batch_data'
require 'docspring/models/submission_batch_with_submissions'
require 'docspring/models/submission_data_request'
require 'docspring/models/submission_data_request_event'
require 'docspring/models/submission_data_request_show'
require 'docspring/models/submission_data_request_token'
require 'docspring/models/submission_preview'
require 'docspring/models/success_error_response'
require 'docspring/models/success_multiple_errors_response'
require 'docspring/models/template'
require 'docspring/models/template_add_fields_response'
require 'docspring/models/template_delete_response'
require 'docspring/models/template_preview'
require 'docspring/models/template_publish_version_response'
require 'docspring/models/update_html_template'
require 'docspring/models/update_submission_data_request_data'
require 'docspring/models/upload_presign_response'

# APIs
require 'docspring/api/pdf_api'

module DocSpring
  class << self
    # Customize default settings for the SDK using block.
    #   DocSpring.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
