=begin
#DocSpring API

#DocSpring provides an API that helps you fill out and sign PDF templates.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'date'
require 'time'

module DocSpring
  class CombinedSubmission
    attr_accessor :id

    attr_accessor :state

    attr_accessor :expired

    attr_accessor :expires_in

    attr_accessor :expires_at

    attr_accessor :processed_at

    attr_accessor :error_message

    attr_accessor :submission_ids

    attr_accessor :source_pdfs

    attr_accessor :metadata

    attr_accessor :password

    attr_accessor :pdf_hash

    attr_accessor :download_url

    attr_accessor :actions

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'state' => :'state',
        :'expired' => :'expired',
        :'expires_in' => :'expires_in',
        :'expires_at' => :'expires_at',
        :'processed_at' => :'processed_at',
        :'error_message' => :'error_message',
        :'submission_ids' => :'submission_ids',
        :'source_pdfs' => :'source_pdfs',
        :'metadata' => :'metadata',
        :'password' => :'password',
        :'pdf_hash' => :'pdf_hash',
        :'download_url' => :'download_url',
        :'actions' => :'actions'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'state' => :'String',
        :'expired' => :'Boolean',
        :'expires_in' => :'Integer',
        :'expires_at' => :'String',
        :'processed_at' => :'String',
        :'error_message' => :'String',
        :'submission_ids' => :'Array<String>',
        :'source_pdfs' => :'Array<Object>',
        :'metadata' => :'Object',
        :'password' => :'String',
        :'pdf_hash' => :'String',
        :'download_url' => :'String',
        :'actions' => :'Array<CombinedSubmissionAction>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'id',
        :'expires_in',
        :'expires_at',
        :'processed_at',
        :'error_message',
        :'password',
        :'pdf_hash',
        :'download_url',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DocSpring::CombinedSubmission` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DocSpring::CombinedSubmission`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      else
        self.state = nil
      end

      if attributes.key?(:'expired')
        self.expired = attributes[:'expired']
      else
        self.expired = nil
      end

      if attributes.key?(:'expires_in')
        self.expires_in = attributes[:'expires_in']
      else
        self.expires_in = nil
      end

      if attributes.key?(:'expires_at')
        self.expires_at = attributes[:'expires_at']
      else
        self.expires_at = nil
      end

      if attributes.key?(:'processed_at')
        self.processed_at = attributes[:'processed_at']
      else
        self.processed_at = nil
      end

      if attributes.key?(:'error_message')
        self.error_message = attributes[:'error_message']
      else
        self.error_message = nil
      end

      if attributes.key?(:'submission_ids')
        if (value = attributes[:'submission_ids']).is_a?(Array)
          self.submission_ids = value
        end
      else
        self.submission_ids = nil
      end

      if attributes.key?(:'source_pdfs')
        if (value = attributes[:'source_pdfs']).is_a?(Array)
          self.source_pdfs = value
        end
      else
        self.source_pdfs = nil
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      else
        self.metadata = nil
      end

      if attributes.key?(:'password')
        self.password = attributes[:'password']
      else
        self.password = nil
      end

      if attributes.key?(:'pdf_hash')
        self.pdf_hash = attributes[:'pdf_hash']
      else
        self.pdf_hash = nil
      end

      if attributes.key?(:'download_url')
        self.download_url = attributes[:'download_url']
      else
        self.download_url = nil
      end

      if attributes.key?(:'actions')
        if (value = attributes[:'actions']).is_a?(Array)
          self.actions = value
        end
      else
        self.actions = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @state.nil?
        invalid_properties.push('invalid value for "state", state cannot be nil.')
      end

      if @expired.nil?
        invalid_properties.push('invalid value for "expired", expired cannot be nil.')
      end

      if @submission_ids.nil?
        invalid_properties.push('invalid value for "submission_ids", submission_ids cannot be nil.')
      end

      if @source_pdfs.nil?
        invalid_properties.push('invalid value for "source_pdfs", source_pdfs cannot be nil.')
      end

      if @metadata.nil?
        invalid_properties.push('invalid value for "metadata", metadata cannot be nil.')
      end

      if @actions.nil?
        invalid_properties.push('invalid value for "actions", actions cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @state.nil?
      state_validator = EnumAttributeValidator.new('String', ["pending", "processed", "error"])
      return false unless state_validator.valid?(@state)
      return false if @expired.nil?
      return false if @submission_ids.nil?
      return false if @source_pdfs.nil?
      return false if @metadata.nil?
      return false if @actions.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] state Object to be assigned
    def state=(state)
      validator = EnumAttributeValidator.new('String', ["pending", "processed", "error"])
      unless validator.valid?(state)
        fail ArgumentError, "invalid value for \"state\", must be one of #{validator.allowable_values}."
      end
      @state = state
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          state == o.state &&
          expired == o.expired &&
          expires_in == o.expires_in &&
          expires_at == o.expires_at &&
          processed_at == o.processed_at &&
          error_message == o.error_message &&
          submission_ids == o.submission_ids &&
          source_pdfs == o.source_pdfs &&
          metadata == o.metadata &&
          password == o.password &&
          pdf_hash == o.pdf_hash &&
          download_url == o.download_url &&
          actions == o.actions
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, state, expired, expires_in, expires_at, processed_at, error_message, submission_ids, source_pdfs, metadata, password, pdf_hash, download_url, actions].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = DocSpring.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
