=begin
#API v1

#DocSpring is a service that helps you fill out and sign PDF templates.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'date'
require 'time'

module DocSpring
  class Template
    attr_accessor :name

    attr_accessor :description

    attr_accessor :public_web_form

    attr_accessor :public_submissions

    attr_accessor :expire_submissions

    attr_accessor :expire_after

    attr_accessor :expiration_interval

    attr_accessor :allow_additional_properties

    attr_accessor :editable_submissions

    attr_accessor :locked

    attr_accessor :webhook_url

    attr_accessor :slack_webhook_url

    attr_accessor :redirect_url

    attr_accessor :id

    attr_accessor :template_type

    attr_accessor :page_dimensions

    attr_accessor :document_url

    attr_accessor :permanent_document_url

    attr_accessor :path

    attr_accessor :parent_folder_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'description' => :'description',
        :'public_web_form' => :'public_web_form',
        :'public_submissions' => :'public_submissions',
        :'expire_submissions' => :'expire_submissions',
        :'expire_after' => :'expire_after',
        :'expiration_interval' => :'expiration_interval',
        :'allow_additional_properties' => :'allow_additional_properties',
        :'editable_submissions' => :'editable_submissions',
        :'locked' => :'locked',
        :'webhook_url' => :'webhook_url',
        :'slack_webhook_url' => :'slack_webhook_url',
        :'redirect_url' => :'redirect_url',
        :'id' => :'id',
        :'template_type' => :'template_type',
        :'page_dimensions' => :'page_dimensions',
        :'document_url' => :'document_url',
        :'permanent_document_url' => :'permanent_document_url',
        :'path' => :'path',
        :'parent_folder_id' => :'parent_folder_id'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'description' => :'String',
        :'public_web_form' => :'Boolean',
        :'public_submissions' => :'Boolean',
        :'expire_submissions' => :'Boolean',
        :'expire_after' => :'Float',
        :'expiration_interval' => :'String',
        :'allow_additional_properties' => :'Boolean',
        :'editable_submissions' => :'Boolean',
        :'locked' => :'Boolean',
        :'webhook_url' => :'String',
        :'slack_webhook_url' => :'String',
        :'redirect_url' => :'String',
        :'id' => :'String',
        :'template_type' => :'String',
        :'page_dimensions' => :'Array<Array<Float>>',
        :'document_url' => :'String',
        :'permanent_document_url' => :'String',
        :'path' => :'String',
        :'parent_folder_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'name',
        :'description',
        :'webhook_url',
        :'slack_webhook_url',
        :'redirect_url',
        :'page_dimensions',
        :'document_url',
        :'permanent_document_url',
        :'parent_folder_id'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DocSpring::Template` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DocSpring::Template`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      else
        self.description = nil
      end

      if attributes.key?(:'public_web_form')
        self.public_web_form = attributes[:'public_web_form']
      else
        self.public_web_form = nil
      end

      if attributes.key?(:'public_submissions')
        self.public_submissions = attributes[:'public_submissions']
      else
        self.public_submissions = nil
      end

      if attributes.key?(:'expire_submissions')
        self.expire_submissions = attributes[:'expire_submissions']
      else
        self.expire_submissions = nil
      end

      if attributes.key?(:'expire_after')
        self.expire_after = attributes[:'expire_after']
      else
        self.expire_after = nil
      end

      if attributes.key?(:'expiration_interval')
        self.expiration_interval = attributes[:'expiration_interval']
      else
        self.expiration_interval = nil
      end

      if attributes.key?(:'allow_additional_properties')
        self.allow_additional_properties = attributes[:'allow_additional_properties']
      else
        self.allow_additional_properties = nil
      end

      if attributes.key?(:'editable_submissions')
        self.editable_submissions = attributes[:'editable_submissions']
      else
        self.editable_submissions = nil
      end

      if attributes.key?(:'locked')
        self.locked = attributes[:'locked']
      else
        self.locked = nil
      end

      if attributes.key?(:'webhook_url')
        self.webhook_url = attributes[:'webhook_url']
      else
        self.webhook_url = nil
      end

      if attributes.key?(:'slack_webhook_url')
        self.slack_webhook_url = attributes[:'slack_webhook_url']
      else
        self.slack_webhook_url = nil
      end

      if attributes.key?(:'redirect_url')
        self.redirect_url = attributes[:'redirect_url']
      else
        self.redirect_url = nil
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'template_type')
        self.template_type = attributes[:'template_type']
      else
        self.template_type = nil
      end

      if attributes.key?(:'page_dimensions')
        if (value = attributes[:'page_dimensions']).is_a?(Array)
          self.page_dimensions = value
        end
      else
        self.page_dimensions = nil
      end

      if attributes.key?(:'document_url')
        self.document_url = attributes[:'document_url']
      else
        self.document_url = nil
      end

      if attributes.key?(:'permanent_document_url')
        self.permanent_document_url = attributes[:'permanent_document_url']
      else
        self.permanent_document_url = nil
      end

      if attributes.key?(:'path')
        self.path = attributes[:'path']
      else
        self.path = nil
      end

      if attributes.key?(:'parent_folder_id')
        self.parent_folder_id = attributes[:'parent_folder_id']
      else
        self.parent_folder_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @public_web_form.nil?
        invalid_properties.push('invalid value for "public_web_form", public_web_form cannot be nil.')
      end

      if @public_submissions.nil?
        invalid_properties.push('invalid value for "public_submissions", public_submissions cannot be nil.')
      end

      if @expire_submissions.nil?
        invalid_properties.push('invalid value for "expire_submissions", expire_submissions cannot be nil.')
      end

      if @expire_after.nil?
        invalid_properties.push('invalid value for "expire_after", expire_after cannot be nil.')
      end

      if @expiration_interval.nil?
        invalid_properties.push('invalid value for "expiration_interval", expiration_interval cannot be nil.')
      end

      if @allow_additional_properties.nil?
        invalid_properties.push('invalid value for "allow_additional_properties", allow_additional_properties cannot be nil.')
      end

      if @editable_submissions.nil?
        invalid_properties.push('invalid value for "editable_submissions", editable_submissions cannot be nil.')
      end

      if @locked.nil?
        invalid_properties.push('invalid value for "locked", locked cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @template_type.nil?
        invalid_properties.push('invalid value for "template_type", template_type cannot be nil.')
      end

      if @path.nil?
        invalid_properties.push('invalid value for "path", path cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @public_web_form.nil?
      return false if @public_submissions.nil?
      return false if @expire_submissions.nil?
      return false if @expire_after.nil?
      return false if @expiration_interval.nil?
      expiration_interval_validator = EnumAttributeValidator.new('String', ["minutes", "hours", "days"])
      return false unless expiration_interval_validator.valid?(@expiration_interval)
      return false if @allow_additional_properties.nil?
      return false if @editable_submissions.nil?
      return false if @locked.nil?
      return false if @id.nil?
      return false if @template_type.nil?
      return false if @path.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] expiration_interval Object to be assigned
    def expiration_interval=(expiration_interval)
      validator = EnumAttributeValidator.new('String', ["minutes", "hours", "days"])
      unless validator.valid?(expiration_interval)
        fail ArgumentError, "invalid value for \"expiration_interval\", must be one of #{validator.allowable_values}."
      end
      @expiration_interval = expiration_interval
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          description == o.description &&
          public_web_form == o.public_web_form &&
          public_submissions == o.public_submissions &&
          expire_submissions == o.expire_submissions &&
          expire_after == o.expire_after &&
          expiration_interval == o.expiration_interval &&
          allow_additional_properties == o.allow_additional_properties &&
          editable_submissions == o.editable_submissions &&
          locked == o.locked &&
          webhook_url == o.webhook_url &&
          slack_webhook_url == o.slack_webhook_url &&
          redirect_url == o.redirect_url &&
          id == o.id &&
          template_type == o.template_type &&
          page_dimensions == o.page_dimensions &&
          document_url == o.document_url &&
          permanent_document_url == o.permanent_document_url &&
          path == o.path &&
          parent_folder_id == o.parent_folder_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, description, public_web_form, public_submissions, expire_submissions, expire_after, expiration_interval, allow_additional_properties, editable_submissions, locked, webhook_url, slack_webhook_url, redirect_url, id, template_type, page_dimensions, document_url, permanent_document_url, path, parent_folder_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = DocSpring.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
