=begin
#API v1

#DocSpring is a service that helps you fill out and sign PDF templates.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'date'
require 'time'

module DocSpring
  class UploadTemplateData
    attr_accessor :add_data_request_submission_id_footers

    attr_accessor :allow_additional_properties

    attr_accessor :description

    attr_accessor :document

    attr_accessor :editable_submissions

    attr_accessor :expiration_interval

    attr_accessor :expire_after

    attr_accessor :expire_submissions

    attr_accessor :footer_html

    attr_accessor :header_html

    attr_accessor :html

    attr_accessor :merge_audit_trail_pdf

    attr_accessor :name

    attr_accessor :public_submissions

    attr_accessor :public_web_form

    attr_accessor :redirect_url

    attr_accessor :scss

    attr_accessor :slack_webhook_url

    attr_accessor :template_type

    attr_accessor :webhook_options

    attr_accessor :webhook_url

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'add_data_request_submission_id_footers' => :'add_data_request_submission_id_footers',
        :'allow_additional_properties' => :'allow_additional_properties',
        :'description' => :'description',
        :'document' => :'document',
        :'editable_submissions' => :'editable_submissions',
        :'expiration_interval' => :'expiration_interval',
        :'expire_after' => :'expire_after',
        :'expire_submissions' => :'expire_submissions',
        :'footer_html' => :'footer_html',
        :'header_html' => :'header_html',
        :'html' => :'html',
        :'merge_audit_trail_pdf' => :'merge_audit_trail_pdf',
        :'name' => :'name',
        :'public_submissions' => :'public_submissions',
        :'public_web_form' => :'public_web_form',
        :'redirect_url' => :'redirect_url',
        :'scss' => :'scss',
        :'slack_webhook_url' => :'slack_webhook_url',
        :'template_type' => :'template_type',
        :'webhook_options' => :'webhook_options',
        :'webhook_url' => :'webhook_url'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'add_data_request_submission_id_footers' => :'Boolean',
        :'allow_additional_properties' => :'Boolean',
        :'description' => :'String',
        :'document' => :'TemplateDocument',
        :'editable_submissions' => :'Boolean',
        :'expiration_interval' => :'String',
        :'expire_after' => :'Float',
        :'expire_submissions' => :'Boolean',
        :'footer_html' => :'String',
        :'header_html' => :'String',
        :'html' => :'String',
        :'merge_audit_trail_pdf' => :'Boolean',
        :'name' => :'String',
        :'public_submissions' => :'Boolean',
        :'public_web_form' => :'Boolean',
        :'redirect_url' => :'String',
        :'scss' => :'String',
        :'slack_webhook_url' => :'String',
        :'template_type' => :'String',
        :'webhook_options' => :'HtmlTemplateDataWebhookOptions',
        :'webhook_url' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'description',
        :'footer_html',
        :'header_html',
        :'html',
        :'name',
        :'redirect_url',
        :'scss',
        :'slack_webhook_url',
        :'webhook_options',
        :'webhook_url'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DocSpring::UploadTemplateData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DocSpring::UploadTemplateData`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'add_data_request_submission_id_footers')
        self.add_data_request_submission_id_footers = attributes[:'add_data_request_submission_id_footers']
      end

      if attributes.key?(:'allow_additional_properties')
        self.allow_additional_properties = attributes[:'allow_additional_properties']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'document')
        self.document = attributes[:'document']
      end

      if attributes.key?(:'editable_submissions')
        self.editable_submissions = attributes[:'editable_submissions']
      end

      if attributes.key?(:'expiration_interval')
        self.expiration_interval = attributes[:'expiration_interval']
      end

      if attributes.key?(:'expire_after')
        self.expire_after = attributes[:'expire_after']
      end

      if attributes.key?(:'expire_submissions')
        self.expire_submissions = attributes[:'expire_submissions']
      end

      if attributes.key?(:'footer_html')
        self.footer_html = attributes[:'footer_html']
      end

      if attributes.key?(:'header_html')
        self.header_html = attributes[:'header_html']
      end

      if attributes.key?(:'html')
        self.html = attributes[:'html']
      end

      if attributes.key?(:'merge_audit_trail_pdf')
        self.merge_audit_trail_pdf = attributes[:'merge_audit_trail_pdf']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'public_submissions')
        self.public_submissions = attributes[:'public_submissions']
      end

      if attributes.key?(:'public_web_form')
        self.public_web_form = attributes[:'public_web_form']
      end

      if attributes.key?(:'redirect_url')
        self.redirect_url = attributes[:'redirect_url']
      end

      if attributes.key?(:'scss')
        self.scss = attributes[:'scss']
      end

      if attributes.key?(:'slack_webhook_url')
        self.slack_webhook_url = attributes[:'slack_webhook_url']
      end

      if attributes.key?(:'template_type')
        self.template_type = attributes[:'template_type']
      end

      if attributes.key?(:'webhook_options')
        self.webhook_options = attributes[:'webhook_options']
      end

      if attributes.key?(:'webhook_url')
        self.webhook_url = attributes[:'webhook_url']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      expiration_interval_validator = EnumAttributeValidator.new('String', ["minutes", "hours", "days"])
      return false unless expiration_interval_validator.valid?(@expiration_interval)
      template_type_validator = EnumAttributeValidator.new('String', ["pdf", "html"])
      return false unless template_type_validator.valid?(@template_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] expiration_interval Object to be assigned
    def expiration_interval=(expiration_interval)
      validator = EnumAttributeValidator.new('String', ["minutes", "hours", "days"])
      unless validator.valid?(expiration_interval)
        fail ArgumentError, "invalid value for \"expiration_interval\", must be one of #{validator.allowable_values}."
      end
      @expiration_interval = expiration_interval
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] template_type Object to be assigned
    def template_type=(template_type)
      validator = EnumAttributeValidator.new('String', ["pdf", "html"])
      unless validator.valid?(template_type)
        fail ArgumentError, "invalid value for \"template_type\", must be one of #{validator.allowable_values}."
      end
      @template_type = template_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          add_data_request_submission_id_footers == o.add_data_request_submission_id_footers &&
          allow_additional_properties == o.allow_additional_properties &&
          description == o.description &&
          document == o.document &&
          editable_submissions == o.editable_submissions &&
          expiration_interval == o.expiration_interval &&
          expire_after == o.expire_after &&
          expire_submissions == o.expire_submissions &&
          footer_html == o.footer_html &&
          header_html == o.header_html &&
          html == o.html &&
          merge_audit_trail_pdf == o.merge_audit_trail_pdf &&
          name == o.name &&
          public_submissions == o.public_submissions &&
          public_web_form == o.public_web_form &&
          redirect_url == o.redirect_url &&
          scss == o.scss &&
          slack_webhook_url == o.slack_webhook_url &&
          template_type == o.template_type &&
          webhook_options == o.webhook_options &&
          webhook_url == o.webhook_url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [add_data_request_submission_id_footers, allow_additional_properties, description, document, editable_submissions, expiration_interval, expire_after, expire_submissions, footer_html, header_html, html, merge_audit_trail_pdf, name, public_submissions, public_web_form, redirect_url, scss, slack_webhook_url, template_type, webhook_options, webhook_url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = DocSpring.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
